- README.md
- package.json
- src/mixins/validatable-http-message.coffee
- src/utils/schema-v4-generator.coffee
- src/validators/headers-json-example.coffee
- src/validators/json-example.coffee
- src/validators/json-schema.coffee
- test/cucumber/step_definitions/validation_errors_thens.coffee
- test/cucumber/step_definitions/validators_steps.coffee
- test/cucumber/support/world.coffee
- test/fixtures.coffee
- test/unit/utils/schema-v4-generator-test.coffee
- test/unit/validators/headers-json-example-validator-test.coffee
- test/unit/validators/json-example-test.coffee
- Headers validated for match of value given in expected are:
```
[
'content-type'
'accept'
'accept-charset'
'accept-encoding'
'accept-language'
]
```
- All other headers are validated only for their presence, so values is are validated.
- All dependencies updated to latest
- Better handling primitive types on root level in JSON example validation
- Strings in JSONs on root level were causing exception
- On the root level was validated only typo of array or object
- All JSON primitive types are now always validated on JSON root level
> Validation only content negotiation significant headers for value match

- src/mixins/validatable-http-message.coffee
- src/utils/tv4-to-headers-message.coffee
- src/validators/headers-json-example.coffee
- src/validators/json-schema.coffee
- test/unit/mixins/validatable-http-message-test.coffee
- test/unit/utils/tv4-to-headers-message-test.coffee
- test/unit/validators/headers-json-example-validator-test.coffee
- get rid with confusing user facing messages with `null` media type
- get rid with redundant error messages from previous stages of validations
- custom messages for headers (get rid with JSON schema validator messages) 
- status code error message includes expected value
Note about implementation:
Tv4 validator can be supplied by custom validation messages, but the "At '/json/pointer'" part of the message is somewhere hardcoded and can't be customized. Due this limitation validation messages  from tv4 validator are parsed and sanitized to be human readable instead of some more sophisticated way how to do it.
> User friendly error messages

- package.json
- scripts/mochify
- scripts/test
The jsonlint dependency taken from fork due to https://github.com/zaach/jsonlint/issues/56.
It's the same solution we are using internally in Apiary.
Supersedes https://github.com/apiaryio/gavel.js/pull/61. Inspired by https://github.com/apiaryio/gavel2html/pull/2.
> Test also by browserify

- README.md
- package.json
- scripts/cucumber.coffee
`@nodejs` tag renamed to `@javascript`
> Update to the latest spec

- .travis.yml
- package.json
Related to https://github.com/apiaryio/dredd/issues/660
**BREAKING CHANGE:** Node 0.10 and 0.12 are not supported anymore. See https://github.com/nodejs/LTS#lts-schedule for details. Node.js 0.10 and 0.12 are both officially dead since 2016-12-31.
> Drop support for Node 0.10 and 0.12

- src/validators/json-schema.coffee
- test/fixtures/invalid-schema-v4-with-refs.json
- test/fixtures/valid-schema-v4-with-refs.json
- test/unit/validators/json-schema-test.coffee
More info [here](https://github.com/apiaryio/gavel.js/issues/25#issuecomment-283205325)
> Detect errors on missing schema refs

- .travis.yml
BREAKING CHANGE: From this release, Gavel.js is not tested on Node 4 anymore. Node 4 end of life is April 2018.
> Drop Node 4 support, test Node 8-10

- package.json
Using `git+https` unfortunately breaks on old machines running Git 2.1.x. It is unclear precisely which versions of Git it breaks, but I tested with two old versions:
* git version 2.1.2 : broken
* git version 2.3.3 : works
Since there should be no reason to use `git+https`, this will simply revert the line which was originally updated in commit 68c08ea.
This fixes issue https://github.com/apiaryio/gavel.js/issues/101
Test case
=======
I tried this branch out on the machine in question and the smallest possible test case I could come up with was to install Gavel directly with `npm install gavel` and see the failure. Then do the same for this PR branch.
```
$ git --version
git version 2.1.2
$ node --version
v8.10.0
$ npm --version
5.6.0
$ npm install apiaryio/gavel.js
npm ERR! Error while …
```
> fix: do not load dependencies with `git+https`

- package.json
- src/mixins/validatable-http-message.coffee
- test/unit/mixins/validatable-http-message-test.coffee
`jsonlint` is unmaintained, and the fork referenced in `gavel` is not published.
my proposal is based on the pull request from @honzajavorek where `jsonlint` is replaced with `json-parse-helpfulerror` instead of `parse-json`. `json-parse-helpfulerror` appears to work in the browser as well as server.
https://github.com/apiaryio/gavel.js/pull/85
> feat: replace jsonlint with json-parse-helpfulerror

- .travis.yml
Recently I'm getting Travis CI jobs failing because the package-lock.json gets modified during the installation and then it fails to do git manipulations as there are unstaged changes which would be "lost".
I'm trying to add `--no-save` to mitigate the problem. It helped in https://github.com/apiaryio/dredd/pull/1151/commits/23cc1645c3bbe4a95492a7486b28031fa01b273a, but so temporarily did some random changes to the Travis CI config in the past... 🙄 Hopefully this is gonna work permanently.
> Do not modify the lock file on CI installs

- lib/utils/schema-v4-generator.js
- lib/validators/headers-json-example.js
- lib/validators/json-example.js
- lib/validators/json-schema.js
- lib/validators/text-diff.js
- package-lock.json
- package.json
- scripts/cov
- test/cucumber/step_definitions/model_steps.js
- test/cucumber/step_definitions/validators_steps.js
- test/cucumber/support/world.js
- Removes CoffeeScript-related dependencies
- Adjusts the usage points of CoffeeScript dependencies
- Removes unnecessary dependencies (`is-type`)
- Removes dependencies that can be replaced by other existing dependencies (`lodash`)
> Clean dependencies

- .travis.yml
- package.json
Drops support for NodeJS version 6.
- Closes #133
> Drops NodeJS version 6 support

- .gitignore
- .npmignore
- .travis.yml
- package-lock.json
- package.json
Adds test coverage collector as a part of `ci:test`. Rewrites the way to get line coverage due to code base decaffeination.
- Closes #144
> refactor: adds test coverage collector

- .eslintrc.js
- .prettierrc
- .travis.yml
- lib/mixins/validatable-http-message.js
- lib/model/http-request.js
- lib/model/http-response.js
- lib/utils/get-type.js
- lib/utils/schema-v4-generator.js
- lib/validators/json-schema.js
- lib/validators/text-diff.js
- package-lock.json
- package.json
- test/unit/validate-test.js
- Adds `eslint` config and npm commands (using Dredd eslint config as an example)
- Adds linting to CI
- Fixes existing source code to prevent violation of eslint rules
- Closes #146
> Adds ESLint

- lib/next/test/integration/validateMessage.test.js
- lib/next/test/unit/units/validateStatusCode.test.js
- lib/next/units/validateStatusCode.js
Adds explicit mapping of `statusCode` validation results to produce expected error messages that include real and expected status codes. Fixes failing tests in Dredd pipeline when using the newest release of Gavel.
- Closes #167
> Maps status code validation error to contain real/expected status codes

- lib/mixins/validatable-http-message.js
- lib/next/test/integration/validateMessage.test.js
- lib/next/units/isValid.js
- lib/next/validateMessage.js
- lib/validate.js
- package-lock.json
- package.json
- Adds `isValid` property on the validation result of Gavel
- Adjusts tests to assert a proper value of `isValid` depending on the validation's input
- Adds deprecation warning when using legacy `isValid()` function from Gavel
- Closes #166 
* Adding a new field to the public API may be a breaking change, considering it also means updating `gavel-spec` to include that field, which breaks previous Gavel spec implementations (https://github.com/apiaryio/gavel-spec/pull/42)
> feat: adds "isValid" property on the validation results

- lib/next/units/validateStatusCode.js
Uses plain string comparison to validate `statusCode` of given HTTP messages. Uses strict comparison since statusCode is normalized to always be a string, and is coerced to an empty string when not set.
- Closes #159 
- One of the reasons we previously used `TextDiff` is because of the `rawData` is produces (result of `validator.validate()`). That `rawData` is asserted by Cucumber tests. We should watch out for that.
> feat: uses plain strings comparison for statusCode validation

- lib/next/test/integration/validateMessage.test.js
- lib/next/test/unit/units/normalize/normalizeHeaders.test.js
- lib/next/test/unit/utils/evolve.test.js
- lib/next/units/coerce/coerceHeaders.js
- lib/next/units/coerce/index.js
- lib/next/units/normalize/normalizeHeaders.js
- lib/next/utils/evolve.js
- lib/next/validateMessage.js
* Separates normalization and coercion to have a single coercion map used for both `real` and `expected` (but in different mode).
* Introduces strict and weak coercion modules.
* Uses strict coercion on `real` HTTP message to ensure even the missing data is coerced. This allows to have proper diffs with the expected message.
* Adds unit tests to `evolve` that supports `strict` mode now.
* Adds unit test for `validateMessage` that asserts expected headers, but given none
- Fixes #179
> fix: uses strict and weak coercion for real and expected messages

- lib/next/test/integration/validateMessage.test.js
- lib/next/validateMessage.js
> BREAKING CHANGE: Validates all expected HTTP message properties
- Checks expected HTTP messages properties to determine which properties to validate (previously: validated if a property is present in both expected and real messages)
- Adds tests that ensure _all_ expected HTTP message properties get validated, even if not present in the real message
- Closes #181
> Checks HTTP message properties on the "expected" message

- lib/units/coerce/index.js
- lib/units/validateBody.js
- test/integration/validate.test.js
- test/unit/units/validateBody.test.js
> feat: coerces missing "body" of the actual HTTP message

- test/cucumber/step_definitions/method_steps.js
- test/cucumber/step_definitions/uri_steps.js
Provides adjustments for Cucumber step definitions to properly execute `gavel-spec` features.
Coupled with https://github.com/apiaryio/gavel-spec/pull/52.
> fix: removes arrow functions to prevent context binding of Cucumber steps

- .eslintrc.js
- test/chai.js
- test/integration/validate.test.js
- test/unit/units/validateBody.test.js
- test/unit/units/validateHeaders.test.js
- test/unit/units/validateMethod.test.js
- test/unit/units/validateStatusCode.test.js
- test/unit/units/validateURI.test.js
These changes introduce custom Chai assertions to use in Gavel unit and integration tests.
- To have less verbose test suites
- To have common assertions integrated into `chai` chainable operators. Common assertions include:
- result/field validity
- expected/real type
- errors
- To get rid of implementation details in test, and centralize validation result references (to rely on validation result structure in a single place–custom assertions declaration)
- To enhance test exceptions with more information about the scenario (include stringified validation result and optional hints)
- Closes #184
> test: introduces custom chai assertions

- lib/units/validateBody.js
- test/unit/units/validateBody.test.js
- test/unit/units/validateBody/getBodySchemaType.test.js
Performs given JSON Schema parsing during body validation to prevent processing of invalid or malformed JSON Schema. **Note that this performs no actual validation either a JSON Schema is a valid JSON Schema.**
- Fixes #203 
- Relates to the issue's origin: https://github.com/apiaryio/drafter/issues/719
- Discovered originally in https://github.com/apiaryio/apiary/commit/6b6c1723153bb0e0e358a1e0cb94fd9dc1b9b277
> Adds json schema parsing check during body validation

- .travis.yml
Uses NodeJS version 12 for CI.
- Relates to https://github.com/apiaryio/dredd/issues/1396
> chore: uses node@12 in travis ci

- README.md
I've noticed a discrepancy in the README, illustrating an error that includes the `values` key. That one has been removed after an internal discussion, and the `fields[fieldName].values` are recommended instead.
> chore: removes "errors[i].values" from the README example

- README.md
- package.json
- typings.d.ts
This pull request adds a manual type declaration for Gavel.
> Note that the type definitions added in this pull request are written _manually_. They are not generated from the code base and, therefore, will not update if the source code changes. 
For Gavel to be usable within TypeScript environment.
> Adds TypeScript type definitions

- test/regression/json-inferred-array.test.js
- Closes #43 
- Relates to https://github.com/apiaryio/dredd/issues/177
If these regression tests verify the expected behavior of root-level array validation and inferred JSON Schema array validation (https://github.com/apiaryio/dredd/issues/177), respective issues can be marked as resolved.
> Adds regression tests for inferred schema array validation

- package-lock.json
- package.json
- rollup.config.js
The current file size of the built bundle is `508KB`. That is caused by a number of factors:
1. The bundle is not compressed.
1. The bundle includes `ajv` module, which size is roughly `200KB`.
This pull request enables bundle compression using `rollup-plugin-terser`.
Here's the analyzis of the uncompressed bundle:
> Uses "terser" plugin to compress the built bundle

- lib/utils/deprecated.js
- lib/utils/warn-on-deprecation.js
- lib/validators/json-schema-legacy.js
This pull request adds a deprecation warning whenever attempted to validate JSON Schema Draft V3 (Amanda). JSON Schema Draft 3 support is going to be dropped in the next major release of Gavel.
- Closes #361
> Adds deprecation warning on JSON Schema Draft 3 usage

- .travis.yml
- Follow up to #533
- Removes Node v8 as a target for TravisCI configuration. Gavel now requires `node >=10`.
> chore: remove node 8 from TravisCI configuration

- package-lock.json
- package.json
Fixes a security vulnerability originating from `serialize-javascript` package. More details from dependabot:
> CVE-2020-7660
high severity
Vulnerable versions: < 3.1.0
Patched version: 3.1.0
serialize-javascript prior to 3.1.0 allows remote attackers to inject arbitrary code via the function "deleteFunctions" within "index.js".
>
>An object such as {"foo": /1"/, "bar": "a\"@__R-<UID>-0__@"} was serialized as {"foo": /1"/, "bar": "a\/1"/}, which allows an attacker to escape the bar key. This requires the attacker to control the values of both foo and bar and guess the value of <UID>. The UID has a keyspace of approximately 4 billion making it a realistic network attack.
>
>The following proof-of-concept calls console.log() when the running eval():
eval('('+ serialize({"foo": /1" + …
> fix(deps): [security] bump "rollup-plugin-terser" from 5.3.0 to 7.0.2

- .github/workflows/ci.yml
As we've migrated from CircleCI, enables GitHub actions for continuous integration in the repo. 
Our current [Dredd GitHub actions](https://github.com/apiaryio/dredd/blob/5154957aace430be28e10c0df68255a92b393c2b/.github/workflows/run-test.yml) are used as inspiration.
> chore: add github actions

- .github/workflows/ci.yml
- package.json
Configures the GitHub Actions pipeline to release Gavel using `semantic-release` automatically upon merges to the `master` branch. 
- [Using `semantic-release` CLI with GitHub Actions](https://github.com/semantic-release/cli#github-actions)
> I wasn't able to use [cycjimmy/semantic-release-action@v2](https://github.com/cycjimmy/semantic-release-action) because it was forbidden for our organization.
> chore: add "semantic-release" to GitHub actions
